version: "3"
services:
  api:
    build: ./api
    ports:
      - "8081:3001"
    depends_on:
      - db
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - NODE_ENV
    container_name: perfanalyzer-api

  dashboard:
    build: ./dashboard
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    container_name: perfanalyzer-dashboard

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
